# ruff: noqa
"""
Configuration for Supervised Fine-Tuning (SFT), Project 5

Phase 2 starts here. Project 4 left us with a ~126M GPT that only knows
how to continue WikiText-style text. This project attaches that base
checkpoint to instruction data and continues training it so it responds
to instructions instead of just continuing them.

PAPER REFERENCES:
-----------------
- "Training language models to follow instructions with human feedback"
  (Ouyang et al., 2022, InstructGPT): the three-stage recipe (SFT ->
  reward model -> RLHF). This project is stage one. InstructGPT computes
  the SFT loss only on tokens the assistant produced; we make that a
  switch (LOSS_ON_RESPONSE_ONLY) so the chapter can compare both choices.
- "Stanford Alpaca: An Instruction-following Llama Model" (Taori et al.,
  2023): the 52k instruction dataset, the "### Instruction:" prompt
  template, and the SFT hyperparameters (lr 2e-5, 3 epochs, batch 128).
  Alpaca itself computes the loss on the FULL sequence, prompt included -
  the two papers disagree and both work; the config documents our choice.
- "Self-Instruct: Aligning Language Models with Self-Generated
  Instructions" (Wang et al., 2023): how Alpaca's instructions were
  generated by GPT-3 from 175 seed tasks.
- "Finetuned Language Models Are Zero-Shot Learners" (Wei et al., 2022,
  FLAN): instruction tuning as multi-task fine-tuning.
- "LIMA: Less Is More for Alignment" (Zhou et al., 2023): 1,000 curated
  examples nearly match 52k noisy ones - quality vs quantity for the
  exercises.

WHAT CHANGES vs PROJECT 4 (and what does not):
----------------------------------------------
- The ARCHITECTURE DOES NOT MOVE. Same 16 layers x 768 x 12 heads x
  16,384 vocab as the pre-trained checkpoint; model.py is a verbatim
  copy of project4_pretrain/model.py. SFT changes the data distribution
  and the loss mask, not the network.
- Lower LEARNING RATE: 2e-5 (Alpaca) vs 2.5e-4 pre-training. The base
  model already sits in a good basin; big steps destroy it (catastrophic
  forgetting of the pre-training distribution).
- Loss on a SUBSET of positions: prompts are inputs, responses are
  targets. Positions holding prompt tokens get label -1 and contribute
  nothing to the cross-entropy (see prepare_data.py / template.py).
- The dataset is now a fixed list of variable-length examples seen for
  ~3 epochs, not an endless stream sampled once. Multiple passes over a
  small set means overfitting is the failure mode to watch.

THE TOKENIZER AND TEMPLATE:
---------------------------
We reuse the project 4 tokenizer unchanged (checkpoints/project4/
tokenizer.pkl, 16,384 vocab). No new special tokens: Alpaca's template
is PLAIN TEXT ("### Instruction:", "### Response:"), so the base model
already knows every symbol in it. A response is terminated by the <EOS>
token (id 3) taught during fine-tuning; generate.py stops when it is
sampled.

One honest limitation: this tokenizer normalizes whitespace (the
WikiText corpus is a word stream; newlines were dropped in chapter 4's
prepare_data). SFT examples therefore encode as one long line. The "###"
markers carry the structure; the model never learns newline placement.
Documented here and in the chapter rather than papered over.
"""

import os

import torch

# =============================================================================
# PATHS (built from __file__, always run scripts from the repo root)
# =============================================================================

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DATA_DIR = os.path.join(PROJECT_ROOT, "data")
RAW_DATA_DIR = os.path.join(DATA_DIR, "alpaca")  # downloaded alpaca JSON
TOKENIZED_DATA_DIR = os.path.join(DATA_DIR, "project5")  # encoded .npy arrays

# Artifacts produced by Project 4 - SFT attaches to these directly.
PROJECT4_CHECKPOINT_DIR = os.path.join(PROJECT_ROOT, "checkpoints", "project4")
BASE_CHECKPOINT = os.path.join(PROJECT4_CHECKPOINT_DIR, "model_final.pt")
TOKENIZER_FILE = os.path.join(PROJECT4_CHECKPOINT_DIR, "tokenizer.pkl")

CHECKPOINT_DIR = os.path.join(PROJECT_ROOT, "checkpoints", "project5")

os.makedirs(CHECKPOINT_DIR, exist_ok=True)

# =============================================================================
# SPECIAL TOKENS (same IDs as chapters 2-4; the base model depends on them)
# =============================================================================

SPECIAL_TOKENS = {
    "<PAD>": 0,
    "<UNK>": 1,
    "<BOS>": 2,
    "<EOS>": 3,
}

# =============================================================================
# TOKENIZER (loaded, never retrained here - see tokenizer.py)
# =============================================================================

# Must equal the base checkpoint's vocabulary (project 4 trained 16,384).
# Used only for validation; the real table comes from the tokenizer pickle.
VOCAB_SIZE = 16_384

# =============================================================================
# ALPACA TEMPLATE (plain-text markers, see template.py)
# =============================================================================

# Every formatted example is:
#   <BOS> {preamble} ### Instruction: {q} [### Input: {c}] ### Response: {a} <EOS>
# Loss is taught on {a} + <EOS> only (LOSS_ON_RESPONSE_ONLY).

# =============================================================================
# DATA CONFIGURATION
# =============================================================================

# Sequences per optimizer step = BATCH_SIZE x GRAD_ACCUM_STEPS = 64.
# Alpaca used 128 at lr 2e-5; 64 with the same LR is the closest our 8 GB
# card gets without sitting at the OOM edge (same shapes as project 4).
BATCH_SIZE = 8  # padded examples per forward pass
GRAD_ACCUM_STEPS = 8  # forward/backward passes per optimizer step
BLOCK_SIZE = 512  # model context length (fixed by the base checkpoint)
MAX_SEQ_LEN = 512  # prepared example length incl. <BOS> and <EOS>; training
# feeds tokens[:, :-1] so the model sees T = 511 <= BLOCK_SIZE.

VAL_EXAMPLES = 1_000  # held-out instructions for the val loss estimate
SMOKE_EXAMPLES = 2_000  # --size small subset for pipeline smoke tests
SEED = 42  # shuffling the dataset and the small subset are both seeded

# =============================================================================
# MODEL ARCHITECTURE (must match the base checkpoint; validated on load)
# =============================================================================

N_EMBD = 768
N_HEAD = 12
N_LAYER = 16
DROPOUT = 0.0
# Project 4's config says "raise dropout if you fine-tune on small data
# later". Alpaca is 52k examples seen 3 times - between a corpus and a
# small set; GPT-2-class SFT runs (Alpaca, InstructGPT stage 1) keep
# dropout off and rely on the short schedule. Stays 0.0; revisit if the
# val loss starts climbing.

# =============================================================================
# TRAINING CONFIGURATION
# =============================================================================

MAX_ITERS = 2_400
# 2,400 steps x 64 examples/step = 153,600 example-visits ~= 3 epochs over
# the ~51,000 training instructions (Alpaca trained 3 epochs). At project
# 4's measured pace (~2.3 s/step at the same batch shape) that is roughly
# an hour and a half; the run's real numbers go to book/src/results.md.

LEARNING_RATE = 2e-5  # Alpaca's SFT learning rate
MIN_LEARNING_RATE = LEARNING_RATE * 0.1  # same cosine floor as project 4
WARMUP_ITERS = 100  # short warmup; the optimizer restarts from zero even
# though the weights do not
WEIGHT_DECAY = 0.1  # repo-wide GPT-3 convention (Alpaca used 0.0; at 3
# epochs the difference is negligible and consistency wins here)
BETA1, BETA2 = 0.9, 0.95  # GPT-3/nanoGPT betas (Alpaca used (0.9, 0.999))
GRAD_CLIP = 1.0

# Loss on response tokens only (InstructGPT) vs the full sequence
# (Alpaca's actual code). train.py --loss_on {response,full} overrides;
# the chapter measures the difference.
LOSS_ON_RESPONSE_ONLY = True

EVAL_INTERVAL = 100  # steps between validation estimates
EVAL_ITERS = 20  # batches averaged per loss estimate
LOG_INTERVAL = 10

USE_BF16 = True  # bf16 autocast, same as project 4 (no scaler needed)
USE_COMPILE = False  # torch.compile: not supported on Windows CUDA builds

# =============================================================================
# INFERENCE CONFIGURATION
# =============================================================================

MAX_NEW_TOKENS = 256  # responses are short; stop comes from <EOS> anyway
TEMPERATURE = 0.7  # instruction following reads better below 0.8
TOP_K = 50

# =============================================================================
# SYSTEM CONFIGURATION
# =============================================================================

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"


# =============================================================================
# VALIDATION / PRINTING
# =============================================================================


def validate_config():
    """Validate that hyperparameters are consistent."""
    assert N_EMBD % N_HEAD == 0, f"n_embd ({N_EMBD}) must be divisible by n_head ({N_HEAD})"
    assert BLOCK_SIZE > 0 and BATCH_SIZE > 0 and GRAD_ACCUM_STEPS > 0
    assert MAX_SEQ_LEN <= BLOCK_SIZE, (
        f"MAX_SEQ_LEN ({MAX_SEQ_LEN}) must fit BLOCK_SIZE ({BLOCK_SIZE})"
    )
    assert MAX_SEQ_LEN > 1, "need at least one context position"
    assert 0 < LEARNING_RATE < 1, "learning_rate must be between 0 and 1"
    assert VOCAB_SIZE - len(SPECIAL_TOKENS) > 0, "vocab too small for special tokens"
    assert VOCAB_SIZE <= 65_536, "vocab must fit in uint16 for the .npy token arrays"
    assert WARMUP_ITERS < MAX_ITERS, "warmup must be shorter than the schedule"
    print("✓ Configuration validated")


def print_config():
    """Print all configuration values."""
    examples_per_step = BATCH_SIZE * GRAD_ACCUM_STEPS
    print("=" * 60)
    print("SUPERVISED FINE-TUNING CONFIGURATION (~125M GPT on Alpaca)")
    print("=" * 60)
    print(f"Base checkpoint:     {os.path.relpath(BASE_CHECKPOINT, PROJECT_ROOT)}")
    print(f"Tokenizer:           {os.path.relpath(TOKENIZER_FILE, PROJECT_ROOT)} (loaded, not retrained)")
    print(f"Vocabulary size:     {VOCAB_SIZE:,}")
    print(f"Block size:          {BLOCK_SIZE} (examples prepared at {MAX_SEQ_LEN})")
    print(f"Layers / heads:      {N_LAYER} / {N_HEAD}")
    print(f"Embedding dim:       {N_EMBD}")
    print(f"Dropout:             {DROPOUT}")
    print("-" * 60)
    print("TRAINING CONFIGURATION")
    print("-" * 60)
    print(f"Batch:               {BATCH_SIZE} seqs x {GRAD_ACCUM_STEPS} accum")
    print(f"  = {examples_per_step} examples per optimizer step")
    print(f"Max iterations:      {MAX_ITERS:,}")
    print(f"  = {MAX_ITERS * examples_per_step:,} example visits")
    print(f"Peak LR:             {LEARNING_RATE} (cosine to {MIN_LEARNING_RATE})")
    print(f"Weight decay:        {WEIGHT_DECAY}")
    print(f"Loss:                response-only" if LOSS_ON_RESPONSE_ONLY else
          f"Loss:                full sequence")
    print(f"Device:              {DEVICE}")
    print("=" * 60)


if __name__ == "__main__":
    validate_config()
    print_config()
